### ISSUE TITLE
Connected phone keeps switching out from headset

### ISSUE THREAD

**Issue by ppietak** [littlecraft/phony#12]
Hello, thanks for such a great project!

I have a small problem with it, but probably I misconfigured something. **I have an issue with compiling from sources PulseAudio v7**, and it might be the problem. But nevertheless, I'll describe it.

When I try to make a call, or answer a call, my phone (which is connected to raspberry) keeps switching I/O (or let's call it "sound source") to a regular microphone/speaker, even though I have "MyBluetoothHeadset" paired, connected and I'm able to choose it. In logs, everything looks fine, no errors, clearly see that events are dispatched (`Call began`, etc) and stuff.

Same happens on iPhone 6S, and on Xiaomi Mi Max 2, so I suppose it isn't strictly phone-related.
Is there a way to tell if I have all correctly configured? And this exemplary Python script uses libraries **in correct versions**?

It's a Raspberry Pi 3B+ with Sabrent USB Sound Card (exactly the same from README). If it comes to Bluetooth dongle, I'm not sure what brand it is, but if needed, I can check it's hardware ID.

**Comment by mutac** [comment]
It might be that ofono isn't able to initialize the hands free profile (HFP).  To help debug the problem, I'd suggest running both `ofonod -n -d` and `bluetoothd -n -d` in the foreground, with debug logging turned on to see if you can catch any signs of a problem.

I haven't tested phony on a Pi3B+, but the broadcom bluetooth part on the Pi3 wasn't compatible with HFP.  If you have a separate bluetooth dongle that you think is compatible, you might try explicitly disabling the built-in bluetooth part on the Pi3B+ to make sure that your dongle is the device that's being used.

I also haven't tested later versions of ofono and bluez.  At the time of writing the README, I narrowed it down to combination of versions of ofono and bluez that worked together to support HFP.  It's quite possible that there have been subsequent updates to either or both that may also work, and may help with the profile switching issue you're seeing.

Also, someone else has documented their own setup experience, which might be helpful to read over (it's a little newer):
https://scribles.net/enabling-hands-free-profile-on-raspberry-pi-raspbian-stretch-by-using-pulseaudio/

If you notice anything that the documentation in this repo lacks, or if you are able to get things working using newer (or pre-packaged) versions of ofono & bluez, I'd love a report.

**Comment by ppietak** [comment]
Thanks a lot for explanation and useful info  👍
I'll try to debug it soon, and provide info about the outcome of this investigation.

**Comment by ppietak** [comment]
Ok, looks like my ofono wasn't configured properly. On Debian Stretch, whole process is a lot easier, because desired versions of libraries are available out of the box.
