### ISSUE TITLE
No Audio while Call is going on (on mono channel)

### ISSUE THREAD

**Issue by hamzakhurshid12** [littlecraft/phony#15]
We are using phony on ubuntu 20 with an external sound card. I have it working, it connects to my android phone and works as a headset perfectly fine.
However, when there is a call going on the phone, it stops working. Everything on console is normal, there is no error, but there is also no sound, and the microphone stops working too.  As soon as the call ends, it again starts working. 

We suspected problem with phone, so we tested it on different android phones of different manufacturers, and different android versions. The problem stays.

Next we did was to switch all audio of phone to mono channel. After doing this, phony stops audio and mic for all sound from phone, be it call audio or non-call audio. So we suspect it has something to do with the audio channel the phone is communicating on.

Thank you for your help!

**Comment by mutac** [comment]
Hi,

When you say that it works as a headset, could you describe what _does_ seem to work?  Are you able to initiate a call via voice?

On possibility is that the audio and mic are being muted, or the audio level is being incorrectly set by phony through [phony/audio/alsa.py](https://github.com/littlecraft/phony/blob/master/src/phony/audio/alsa.py).  Are you able to view the state of your audio device in e.g. alsamixer while a call is going on?

Another idea is to check the pulseaudio and ofono logs (you may need to enable detailed logging in their respective config files), to see if there are any underlying errors that occur.  It's possible that the audio gateway between your bluetooth adapter and your audio card isn't being correctly set up.

-Matt
