### ISSUE TITLE
No audio on Raspberry pi

### ISSUE THREAD

**Issue by roxane11** [littlecraft/phony#9]
Hi, I am using Raspi3 with external bluetooth dongle BCM20702A0 and external USB sound card. I am able to kick a call from cranky but there is no audio both the sides. Any suggestions which direction to head to ?

Oct 20 11:15:41 raspberrypi cranky[860]: 2017-10-20 11:15:41.903 phony.headset.HandsFreeHeadset                               INFO     -> HandsFreeHeadset.dial(4849590001)
Oct 20 11:15:41 raspberrypi cranky[860]: 2017-10-20 11:15:41.904 phony.headset.HandsFreeHeadset                               INFO     -> HandsFreeHeadset.unmute_speaker()
Oct 20 11:15:41 raspberrypi cranky[860]: 2017-10-20 11:15:41.904 phony.audio.alsa.Alsa                                        DEBUG    ** Alsa.unmute_speaker()
Oct 20 11:15:41 raspberrypi cranky[860]: 2017-10-20 11:15:41.905 phony.headset.HandsFreeHeadset                               INFO     <- HandsFreeHeadset.unmute_speaker()
Oct 20 11:15:41 raspberrypi cranky[860]: 2017-10-20 11:15:41.906 phony.headset.HandsFreeHeadset                               INFO     -> HandsFreeHeadset.unmute_microphone()
Oct 20 11:15:41 raspberrypi cranky[860]: 2017-10-20 11:15:41.906 phony.audio.alsa.Alsa                                        DEBUG    ** Alsa.unmute_microphone()
Oct 20 11:15:41 raspberrypi cranky[860]: 2017-10-20 11:15:41.907 phony.headset.HandsFreeHeadset                               INFO     <- HandsFreeHeadset.unmute_microphone()
Oct 20 11:15:41 raspberrypi cranky[860]: 2017-10-20 11:15:41.907 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    ** OfonoHfpAg.dial(4849590001)
Oct 20 11:15:42 raspberrypi cranky[860]: 2017-10-20 11:15:42.219 phony.headset.HandsFreeHeadset                               INFO     <- HandsFreeHeadset.dial(4849590001)
Oct 20 11:15:42 raspberrypi cranky[860]: 2017-10-20 11:15:42.221 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    -> OfonoHfpAg._call_added(/hfp/org/bluez/hci0/dev_6C_40_08_64_27_7...)
Oct 20 11:15:42 raspberrypi cranky[860]: 2017-10-20 11:15:42.229 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          INFO     dialing: 4849590001
Oct 20 11:15:42 raspberrypi cranky[860]: 2017-10-20 11:15:42.230 phony.headset.HandsFreeHeadset                               INFO     ** HandsFreeHeadset._call_began(/hfp/org/bluez/hci0/dev_6C_40_08_64_27_7...)
Oct 20 11:15:42 raspberrypi cranky[860]: 2017-10-20 11:15:42.230 phony.examples.cranky.hmi.HandCrankTelephoneControls         DEBUG    ** HandCrankTelephoneControls._call_began(/hfp/org/bluez/hci0/dev_6C_40_08_64_27_7...)
Oct 20 11:15:42 raspberrypi cranky[860]: 2017-10-20 11:15:42.231 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    <- OfonoHfpAg._call_added(/hfp/org/bluez/hci0/dev_6C_40_08_64_27_7...)
Oct 20 11:15:42 raspberrypi cranky[860]: 2017-10-20 11:15:42.232 dbus.connection                                              ERROR    Exception in handler for D-Bus signal:
Oct 20 11:15:42 raspberrypi cranky[860]: Traceback (most recent call last):
Oct 20 11:15:42 raspberrypi cranky[860]: File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
Oct 20 11:15:42 raspberrypi cranky[860]: self._handler(*args, **kwargs)
Oct 20 11:15:42 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/phony/base/log.py", line 112, in call_wrapper
Oct 20 11:15:42 raspberrypi cranky[860]: return method(*args, **kwargs)
Oct 20 11:15:42 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/phony/bluetooth/profiles/handsfree/ofono.py", line 260, in _call_added
Oct 20 11:15:42 raspberrypi cranky[860]: listener(path)
Oct 20 11:15:42 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/phony/base/log.py", line 125, in call_wrapper
Oct 20 11:15:42 raspberrypi cranky[860]: return method(*args, **kwargs)
Oct 20 11:15:42 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/phony/headset.py", line 277, in _call_began
Oct 20 11:15:42 raspberrypi cranky[860]: listener(path)
Oct 20 11:15:42 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/phony/base/log.py", line 125, in call_wrapper
Oct 20 11:15:42 raspberrypi cranky[860]: return method(*args, **kwargs)
Oct 20 11:15:42 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/phony/examples/cranky/hmi.py", line 180, in _call_began
Oct 20 11:15:42 raspberrypi cranky[860]: self._state.call_began()
Oct 20 11:15:42 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 272, in fn
Oct 20 11:15:42 raspberrypi cranky[860]: "event %s inappropriate in current state %s" % (event, self.current))
Oct 20 11:15:42 raspberrypi cranky[860]: FysomError: event call_began inappropriate in current state in_call
Oct 20 11:15:48 raspberrypi cranky[860]: 2017-10-20 11:15:48.084 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    -> OfonoHfpAg._call_properties_changed(State, alerting)
Oct 20 11:15:48 raspberrypi cranky[860]: 2017-10-20 11:15:48.084 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    <- OfonoHfpAg._call_properties_changed(State, alerting)
Oct 20 11:15:49 raspberrypi cranky[860]: 2017-10-20 11:15:49.982 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    -> OfonoHfpAg._call_properties_changed(State, active)
Oct 20 11:15:49 raspberrypi cranky[860]: 2017-10-20 11:15:49.982 phony.headset.HandsFreeHeadset                               INFO     ** HandsFreeHeadset._call_began(/hfp/org/bluez/hci0/dev_6C_40_08_64_27_7...)
Oct 20 11:15:49 raspberrypi cranky[860]: 2017-10-20 11:15:49.983 phony.examples.cranky.hmi.HandCrankTelephoneControls         DEBUG    ** HandCrankTelephoneControls._call_began(/hfp/org/bluez/hci0/dev_6C_40_08_64_27_7...)
Oct 20 11:15:49 raspberrypi cranky[860]: 2017-10-20 11:15:49.984 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    <- OfonoHfpAg._call_properties_changed(State, active)
Oct 20 11:15:49 raspberrypi cranky[860]: 2017-10-20 11:15:49.984 dbus.connection                                              ERROR    Exception in handler for D-Bus signal:
Oct 20 11:15:49 raspberrypi cranky[860]: Traceback (most recent call last):
Oct 20 11:15:49 raspberrypi cranky[860]: File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
Oct 20 11:15:49 raspberrypi cranky[860]: self._handler(*args, **kwargs)
Oct 20 11:15:49 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/phony/base/log.py", line 112, in call_wrapper
Oct 20 11:15:50 raspberrypi cranky[860]: return method(*args, **kwargs)
Oct 20 11:15:50 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/phony/bluetooth/profiles/handsfree/ofono.py", line 278, in _call_properties_changed
Oct 20 11:15:50 raspberrypi cranky[860]: listener(path)
Oct 20 11:15:50 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/phony/base/log.py", line 125, in call_wrapper
Oct 20 11:15:50 raspberrypi cranky[860]: return method(*args, **kwargs)
Oct 20 11:15:50 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/phony/headset.py", line 277, in _call_began
Oct 20 11:15:50 raspberrypi cranky[860]: listener(path)
Oct 20 11:15:50 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/phony/base/log.py", line 125, in call_wrapper
Oct 20 11:15:50 raspberrypi cranky[860]: return method(*args, **kwargs)
Oct 20 11:15:50 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/phony/examples/cranky/hmi.py", line 180, in _call_began
Oct 20 11:15:50 raspberrypi cranky[860]: self._state.call_began()
Oct 20 11:15:50 raspberrypi cranky[860]: File "/usr/local/lib/python2.7/dist-packages/fysom/__init__.py", line 272, in fn
Oct 20 11:15:50 raspberrypi cranky[860]: "event %s inappropriate in current state %s" % (event, self.current))
Oct 20 11:15:50 raspberrypi cranky[860]: FysomError: event call_began inappropriate in current state in_call
Oct 20 11:15:50 raspberrypi cranky[860]: 2017-10-20 11:15:49.987 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    -> OfonoHfpAg._call_properties_changed(StartTime, 2017-10-20T11:15:49-0500)
Oct 20 11:15:50 raspberrypi cranky[860]: 2017-10-20 11:15:49.987 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    <- OfonoHfpAg._call_properties_changed(StartTime, 2017-10-20T11:15:49-0500)
Oct 20 11:15:53 raspberrypi cranky[860]: 2017-10-20 11:15:53.360 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    -> OfonoHfpAg._call_properties_changed(State, disconnected)
Oct 20 11:15:53 raspberrypi cranky[860]: 2017-10-20 11:15:53.360 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    <- OfonoHfpAg._call_properties_changed(State, disconnected)
Oct 20 11:15:53 raspberrypi cranky[860]: 2017-10-20 11:15:53.361 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    -> OfonoHfpAg._call_removed(/hfp/org/bluez/hci0/dev_6C_40_08_64_27_7...)
Oct 20 11:15:53 raspberrypi cranky[860]: 2017-10-20 11:15:53.362 phony.headset.HandsFreeHeadset                               INFO     ** HandsFreeHeadset._call_ended(/hfp/org/bluez/hci0/dev_6C_40_08_64_27_7...)
Oct 20 11:15:53 raspberrypi cranky[860]: 2017-10-20 11:15:53.363 phony.examples.cranky.hmi.HandCrankTelephoneControls         DEBUG    ** HandCrankTelephoneControls._call_ended(/hfp/org/bluez/hci0/dev_6C_40_08_64_27_7...)
Oct 20 11:15:53 raspberrypi cranky[860]: 2017-10-20 11:15:53.364 phony.bluetooth.profiles.handsfree.ofono.OfonoHfpAg          DEBUG    <- OfonoHfpAg._call_removed(/hfp/org/bluez/hci0/dev_6C_40_08_64_27_7...)

**Comment by mutac** [comment]
It sort of looks like an exception is occurring in the HMI event handlers: `phony/examples/cranky/src/phony/examples/cranky/hmi.py`, and I am wondering if that is somehow leading to the disconnection of the "audio gateway" (OfonoHfpAg).

How did the call get initiated, are you using the debug REPL?  The HMI module is rather strict in that it will assert if an event comes in while the HMI is in an unexpected state.  Cranky is also a pretty silly use-case, and the over-restrictiveness of the HMI might have broken the `dial` command.  I think that I should probably include an even simpler example...

Anyway, in `examples/cranky/src/phony/examples/cranky/hmi.py`, if you change this line:

`{'name': 'call_began',        'src': 'initiating_call',         'dst': 'in_call'},`

to be this:

`{'name': 'call_began',        'src': '*',         'dst': 'in_call'},`

I wonder if that would allow the `dial` debug command to function again.

There may also be another issue going on, that's unrelated to the crummy HMI code, and if so, the log files of pulseaudio and ofonod would likely have some clues.  When I needed to debug these kinds of issues, I ended up running ofonod manually starting it `sudo ofonod -n -d`, which will print logging to the console.  If you start pulseaudio as a service, you can edit `/etc/pulse/daemon.conf` or `/user/local/etc/pulse/daemon.conf` and change ` log-level = notice` to ` log-level = debug`, and restart pulseaudio.  The logs should then be available via journald.

**Comment by roxane11** [comment]
I have captured cranky and pulseaudio logs. Please suggest. Your help is highly appreciated !

[pulseverbose.log](https://github.com/littlecraft/phony/files/1403796/pulseverbose.log)
[cranky_logs.txt](https://github.com/littlecraft/phony/files/1403797/cranky_logs.txt)

**Comment by roxane11** [comment]
The problem looks like in starting dbus. Tried every possible thing. This doesn't work anymore. Please help

**Comment by mutac** [comment]
The installation scripts of phony and cranky attempt to set up the necessary connections between pulseaudio, dbus, and ofono.  In addition to that, the scripts attempt to setup pulseaudio to run in system mode, so that everything can run without X11.  It kind of looks like the pulseaudio instance in your log is not actually running as the system user (and is launched via systemd), but as your user 'pi'.  Are you running pulseaudio manually?

It appears that pulseaudio is not attempting to use ofono as the headset backend, judging by this line:
```(   1.142|   0.000) D: [pulseaudio] backend-native.c: Bluetooth Headset Backend API support using the native backend```

If that's the case, your phone is actually being seen by pulseaudio as a media device, and not as a phone.  Incoming or outgoing calls would then not be reported to phony.

Without knowing more of what you've done to get to this point it is hard to say what would be causing that.  It isn't clear if this is a dbus issue, or if your instance of pulseaudio is configured correctly to attach to ofono.  Did you install phony and cranky using the installation scripts?  What operating system are you running on your PI?  Are you sure that ofono is running, do you have a log file for it?  The cranky installation scripts in particular were only tested on raspian Jessie, and they are important to set up the system to a) run pulseaudio in a way that does not require X11, b) sets up pulseaudio so that it can talk to ofono, and c) set the correct user and dbus permissions for the whole rigmarole to work together, so it is entirely possible that they aren't 100% portable.

I'd recommend reading this:
https://freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Bluetooth/#index5h2

And verifying that the following line is present in your `/etc/pulse/default.pa` and/or `/usr/local/etc/pulse/default.pa`

```load-module module-bluetooth-discover headset=ofono```

The more information you can provide the better, as this could conceivably be used to improve the installation scripts or documentation.

**Comment by shahtapan** [comment]
Could you please tell us which python version we should use.  If i run the below command i get error because inside the script it is written as #!/usr/bin/python3
pi@raspberrypi:~/ofono $ test/list-modems
Traceback (most recent call last):
  File "test/list-modems", line 3, in <module>
    import dbus
ImportError: No module named 'dbus'

If i run with python it gives proper results ( python version points to 2.7)
pi@raspberrypi:~/ofono $ python test/list-modems
[ /hfp/org/bluez/hci1/dev_xx_xx_xx_xx]
    Features = net
    Emergency = 0
    Powered = 1
    Lockdown = 0
    Interfaces = org.ofono.VoiceCallManager org.ofono.CallVolume org.ofono.Handsfree org.ofono.NetworkRegistration
    Online = 1
    Serial = xx:xx:xx:xx:xx:xx
    Type = hfp
    Name = Galaxy S7
    [ org.ofono.VoiceCallManager ]
        EmergencyNumbers = 08 000 999 110 112 911 118 119
    [ org.ofono.CallVolume ]
        Muted = 0
        SpeakerVolume = 50
        MicrophoneVolume = 50
    [ org.ofono.Handsfree ]
        Features = three-way-calling echo-canceling-and-noise-reduction voice-recognition release-all-held release-specified-active-call private-chat create-multiparty hf-indicators
        EchoCancelingNoiseReduction = 1
        InbandRinging = 1
        DistractedDrivingReduction = 0
        BatteryChargeLevel = 5
        VoiceRecognition = 0
    [ org.ofono.NetworkRegistration ]
        Status = registered
        Strength = 80
        Mode = auto-only
        Name = T-Mobile

I started the pulseaudio manually.

Could you please help us?

**Comment by shahtapan** [comment]
pi@raspberrypi:~ $ /usr/local/bin/pulseaudio --start
N: [pulseaudio] main.c: System mode refused for non-root user. Only starting the D-Bus server lookup service.
D: [pulseaudio] conf-parser.c: Parsing configuration file '/home/pi/.config/pulse/client.conf'
I: [pulseaudio] main.c: Daemon startup successful.

**Comment by shahtapan** [comment]
Hi Matt. We are able to make call . thanks for your help.
Could you please let us know how to record and inject audio via bluetooth channel?

Is there any specific commands for play and record?

**Comment by shahtapan** [comment]
Hi Matt,

Thanks for providing the information. Now we are able to play and record the audio files via bluetooth.
One more question.
Is there any way to connect multiple bluetooth dongle and connect to multiple mobile devices and have them running running simultaneously?

for e.g
One Raspberry Pi - Multiple bluetooth dongle connected to mobile devices (one to one mapping)
Kindly provide the solution if you already know it.

Thanks in advance :)
